/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as WishlistImport } from "./routes/wishlist";

// Create/Update Routes

const WishlistRoute = WishlistImport.update({
  id: "/wishlist",
  path: "/wishlist",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/wishlist": {
      id: "/wishlist";
      path: "/wishlist";
      fullPath: "/wishlist";
      preLoaderRoute: typeof WishlistImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/wishlist": typeof WishlistRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/wishlist": typeof WishlistRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/wishlist": typeof WishlistRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/wishlist";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/wishlist";
  id: "__root__" | "/" | "/wishlist";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WishlistRoute: typeof WishlistRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WishlistRoute: WishlistRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/wishlist"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/wishlist": {
      "filePath": "wishlist.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
